// <auto-generated />
#nullable enable
using System;
using System.Drawing;
using System.IO;
using System.Globalization;
using System.Resources;

namespace GPhoto.Properties
{
    internal static class Resources
    {
        private static ResourceManager? resourceMan;

        private static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new ResourceManager("GPhoto.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Returns the default image as a new System.Drawing.Bitmap instance.
        /// </summary>
        internal static Bitmap? Default
        {
            get
            {
                try
                {
                    var b64 = ResourceManager.GetString("DefaultImage", CultureInfo.CurrentUICulture);
                    if (string.IsNullOrEmpty(b64)) return null;
                    var bytes = Convert.FromBase64String(b64);
                    using var ms = new MemoryStream(bytes);
                    return new Bitmap(ms);
                }
                catch
                {
                    return null;
                }
            }
        }

        /// <summary>
        /// Returns the application icon from embedded resources.
        /// </summary>
        internal static Icon? AppIcon
        {
            get
            {
                try
                {
                    var assembly = typeof(Resources).Assembly;
                    using var stream = assembly.GetManifestResourceStream("GPhoto.ico.icon.ico");
                    if (stream == null) return null;
                    return new Icon(stream);
                }
                catch
                {
                    return null;
                }
            }
        }
    }
}
